### ISSUE TITLE
Use args instead of env variables in Dockerfile

### ISSUE THREAD

**Issue by ghost** [nginx-proxy/docker-gen#321]
By using arg instead of variables in Dockerfile it will be easy to build docker-gen for different architectures, e.g. I can have following docker compose file and it will work correctly:

```
version: '3'
services:
  nginx-gen:
    build:
      context: https://github.com/dealancer/docker-gen.git
      args:
        - ARCHITECTURE=armhf
...
```
