### ISSUE TITLE
not restart nginx

### ISSUE THREAD

**Issue by tomfun** [nginx-proxy/docker-gen#475]
I have used docker-gen for years on amd64, but recently tried arm [raspberrypi.org](https://www.raspberrypi.org/) and found problem that template generated but nginx container is not reloading config.
If I stop some container I see changes tempated result but nginx still hold old configuration. But if I send HUP manually to nginx all is good.

Manual Reload command: `docker-compose --project-name nginx kill -s HUP nginx`
docker-compose (part):

```yaml
version: '3'
services:
  nginx:
    restart: always
    volumes:
      - ./data:/usr/share/nginx/html:ro
      - ./configs:/etc/nginx:ro
    ports:
      - '80:80'
      - '443:443'

  dynamic-docker-proxy:
    image: jwilder/docker-gen
    restart: always
    volumes:
      - ./configs/conf.d:/etc/nginx/conf.d/
      - ./templates:/etc/docker-gen/templates
      - /var/run/docker.sock:/tmp/docker.sock:rw
    command: -notify-sighup nginx_nginx_1 -watch -only-exposed /etc/docker-gen/templates/dynamic.proxy.tmpl /etc/nginx/conf.d/dynamic.proxy.conf
    network_mode: "none"
``` 

sudo docker version:
```
Client: Docker Engine - Community
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:01:19 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.21
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       3056208
  Built:            Tue Oct 25 17:59:41 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.10
  GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
Installed by official https://docs.docker.com/engine/install/debian/
```
containerd.io is already the newest version (1.6.10-1).
docker-ce-cli is already the newest version (5:20.10.21~3-0~debian-bullseye).
docker-ce is already the newest version (5:20.10.21~3-0~debian-bullseye).
```

As I understand `-notify-sighup nginx_nginx_1` do the magic and must send nginx reload sig

Thanks for any help
