### ISSUE TITLE
How to stop requesting of NEW certificates?

### ISSUE THREAD

**Issue by richardARPANET** [nginx-proxy/docker-gen#505]
Whenever I restart the container, it goes through all my domains and requests NEW certs. I want it to use the existing non-expired certs.

This is a problem as it is now hitting 429 error from letsencrypt server.

**Comment by kortenkamp** [comment]
@richardARPANET — as I run into the same problem right now: can you post here what you did to solve it? Thanks a lot.

**Comment by richardARPANET** [comment]
@kortenkamp Cant remember sadly, however here's my docker-compose file incase it has any clues.

```
version: '3.6'
services:
  nginx:
    image: nginx
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/nginx-proxy/conf.d:/etc/nginx/conf.d:rw
      - /data/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /data/nginx-proxy/html:/usr/share/nginx/html:rw
      - /data/nginx-proxy/certs:/etc/nginx/certs:rw

  nginx-gen:
    image: nginxproxy/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: unless-stopped
    volumes:
      - /data/nginx-proxy/conf.d:/etc/nginx/conf.d:rw
      - /data/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /data/nginx-proxy/html:/usr/share/nginx/html:rw
      - /data/nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:rw

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-letsencrypt
    restart: unless-stopped
    volumes:
      - /data/nginx-proxy/conf.d:/etc/nginx/conf.d:rw
      - /data/nginx-proxy/vhost.d:/etc/nginx/vhost.d:rw
      - /data/nginx-proxy/html:/usr/share/nginx/html:rw
      - /data/nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/nginx-proxy/acme.sh:/etc/acme.sh:rw

    environment:
      NGINX_DOCKER_GEN_CONTAINER: "nginx-gen"
      NGINX_PROXY_CONTAINER: "nginx"
      REUSE_PRIVATE_KEYS: "true"
      RENEW_PRIVATE_KEYS: "false"
      DEFAULT_EMAIL: "enquiries@example.com"
networks:
  default:
    external:
      name: nginx-proxy

```
